UI: Added hostname to LogBox title
bitburner-official/bitburner-src pull request #478
Opened 2023-04-17 22:53 UTC by unkwntech

I added the hostname to the title bar of the log/tail window to indicate which server the script that is being viewed is running on.

![Screenshot of log window showing the hostname "home" displayed as a prefix in the title bar.](https://i.imgur.com/ZvGbzYu.png)

2023-04-18 08:00 UTC, Snarling requested changes

2023-04-18 08:00 UTC, Snarling commented on src/ui/React/LogBoxManager.tsx
> +    const server = GetServer(script.server);
script.server here is already a hostname, is there a reason you're doing another lookup to fetch the actual server using that name?

2023-04-18 08:00 UTC, Snarling commented on src/ui/React/LogBoxManager.tsx
> +    const t = `${hostname}${script.filename} ${script.args.map((x: ScriptArg): string => `${x}`).join(" ")}`;
```suggestion
    const t = `${script.server}: ${script.filename} ${script.args.join(" ")}`;
```
It's pre-existing code, but that map function to turn arguments into strings is also not needed - [joining them](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join#description) already does that.

2023-04-24 14:30 UTC, Snarling approved these changes

2023-04-24 14:33 UTC, merged

2023-04-24 15:49 UTC, brunnerh commented
I feel like this should be an option, my titles already don't fit fairly often.
![image](https://user-images.githubusercontent.com/834235/234049157-409058e9-5a1d-42d0-a9bf-5b71b0bc0ec3.png)

2023-04-24 17:15 UTC, Snarling commented
Yeah I can see how that would be a problem. I'll open an issue for it.

2023-05-09 10:51 UTC, d0sboots commented
I am undoing this in #508, but it adds the ability to both get the current title and set a custom title, so hopefully that makes it easy to reimplement for the scripts where you want it.