MISC Readthedocs configuration that redirects to this repo
bitburner-official/bitburner-src pull request #833
Opened 2023-09-27 18:11 UTC by Hoekstraa

This PR reintroduces a ReadTheDocs configuration, that in combination with some tweaks on the ReadTheDocs side (which I will make once this merges, but have tested with my own fork) redirects people from ReadTheDocs to the documentation available at https://github.com/bitburner-official/bitburner-src/blob/dev/src/Documentation/doc/index.md.

It:
- closes #824
- stops the e-mails the ReadTheDocs admins have been getting (finally!!)
- redirects people to up-to-date documentation, what more do you want?

2023-09-27 22:05 UTC, d0sboots commented
Is it possible to not hardcode the repo + branch name? This is not entirely theoretical; we used to publish different readthedocs from different branches, and there's still the dev/beta/release split in terms of versions.

2023-10-03 05:34 UTC, Snarling commented
Yeah there should be the ability to point to stable instead of dev.

If we point to dev all the time, newly added api functionality from the current dev cycle will be shown to players who are playing stable branch. Additionally, when we are doing the 3.0 dev cycle and adding in all the major API breaks we want to do piece by piece, the existing documentation for the stable version essentially "disappears."

But with RTD being deprecated to just be a redirect, I guess it's not a big deal. But if it's not simple to make it capable of being dynamic, I think it should just statically target the stable branch instead of dev.

2023-10-03 05:36 UTC, Snarling commented
Actually the more I think about it, just always redirecting the RTD to stable branch is probably the way to go. If players want dev branch documentation, they can use the links from ingame in the dev version.

2023-10-03 06:24 UTC, Snarling requested changes
I would make the change myself but I don't know if it requires changes on the RTD side as well. I think we should link RTD's to the stable branch docs instead of dev, to prevent normal players from being redirected to docs that aren't for their current version.

2023-10-03 08:15 UTC, Hoekstraa commented
Will change to stable when I have the time. I was checking some things on the RTD side and there's some issues there still.
I'm going to have to do some more work, because RTD seems to have removed some features over time that we could've used for this. E.g. it seems to me they (actively?) try to prevent projects from doing these types of redirects.

Plan now is to test if we can remove everything and only have a 404 page that redirects to the docs.
I'll make sure that one will link to the stable version. ;)

2023-10-03 21:41 UTC, d0sboots commented
> E.g. it seems to me they (actively?) try to prevent projects from doing these types of redirects.

I could have sworn I read some docs (on the RTD side) that talked about how you could do exactly this. Have they broken that?

2023-10-03 21:57 UTC, Hoekstraa commented
Yeah, I've sent some docs about it in the Discord, those exact pieces of
advice and even the official documentation refer to an option that just
isn't available (anymore) it seems. Specifically the 'force redirect'
option if I remember it correctly off the top of my head. I'm not sure, but
it might be a ReadTheDocs premium/gold/enterprise option, it has been
removed, or it never got shipped, but it's not where I expect it to be.

This essentially breaks redirecting to a specific link.
This is important as users might not arrive at the root of the
documentation, but say search for gang info and land at the gang info. In
every case I've found it adds the subcontents of the url after the
redirect. For example:

bla.readthedocs.blegh/en/latest/randompageaboutgangs

Will turn into:

github.com/bitburner-official/bla-src/bla/bla/src/Documentation/index.md/randompageaboutgangs

Regardless of type of redirect. Trust me, I've most assuredly tried more
than 60 variations of them by now.
Overall the redirection is a big ol' mess. Hence my next idea would be to
strip the readthedocs of anything and use a custom 404 with a meta
redirect, so that we can avoid having to deal with readthedocs' internal
router.

Sorry for the crappy explanation as I'm on my phone as I'm writing this
through e-mail.
Let me know either here or on Discord if anything's unclear.

2023-10-17 06:17 UTC, Snarling commented
Have you tried including a useless html query at the end of the URL? Then you'd end up with a url like:
https://github.com/bitburner-official/bitburner-src/blob/stable/src/Documentation/doc/index.md?none/of/this/does/anything.md

Which still points to the main documentation page.

2023-10-23 16:17 UTC, Snarling commented
@Hoekstraa Did you see my previous comment about possibly using a query to throw away extra path info and always land at the same page? Not sure if it will work but it may be worth a shot.

2023-10-23 16:20 UTC, Hoekstraa commented
@Snarling Thank you for the suggestion. Sorry for the delay, I had some important work to do last week so didn't have the time to dig into it. I'm actually looking at it right this moment, and the query suggestion seems to help in the case I described. It doesn't seem to work 100% of the time as there's some other edge cases, so we still need to pull some code into the repo.
I'm hoping to get a fix out this evening.

2023-10-23 17:12 UTC, Hoekstraa commented
Changes on the RTD side have been made for bitburner-official.readthedocs.io.
We just need the changes made here for it all to line up and redirect all requests to that webpage to the Github docs.

Hydro is going to try and get access for the other pages (bitburner, bitburner-beta) next week he said. So we'll get those aligned if and when we can.

2023-10-24 08:40 UTC, Snarling commented
Sorry, just now checking back on this. Are the changes here still needed? I'm seeing all of these pages now redirect to the documentation, so it looks like you got it working without any changes needed here?

https://bitburner-src.readthedocs.io/
https://bitburner-src.readthedocs.io/en/
https://bitburner-src.readthedocs.io/en/latest/
https://bitburner-src.readthedocs.io/en/latest/advancedgameplay/

2023-10-24 09:03 UTC, Hoekstraa commented
Oh! Sorry for the confusion. Bitburner-src is actually my testing environment for this (based on my branch).
It's bitburner-official leading to this repository, and bitburner and bitburner-beta leading to the older repositories.
Once we get ownership of bitburner and bitburner-beta we'll redirect them to here too.

The thing is that search engines will point to either bitburner-official, but most likely bitburner and bitburner-beta.
So if we want to redirect them, we need the changes made in this PR.

I'm glad though that https://bitburner-src.readthedocs.io/ works for you, because that means my demo/PR works correctly ;)

2023-10-24 09:05 UTC, Hoekstraa commented
So once we merge this PR, https://bitburner-official.readthedocs.io/ should behave the same, and when we get control of the others, they can be converted to use this PR too. So this is the only change necessary.

2023-10-24 09:11 UTC, Snarling commented
Oh okay, I misunderstood lol. I was wondering why searching was never bringing that one up.

2023-10-24 09:11 UTC, merged